# Generated by Django 3.2.9 on 2021-12-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='email',
            new_name='Email',
        ),
    ]
