# Generated by Django 3.2.9 on 2021-12-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rename_email_personal_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='social',
            new_name='Social',
        ),
    ]
