# Generated by Django 3.2.9 on 2021-12-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_rename_social_personal_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='Social',
            new_name='Socials',
        ),
    ]
