# Generated by Django 3.2.9 on 2021-12-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_rename_social_personal_socials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='PhoneNumber',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='PersonalSummary',
            new_name='Summary',
        ),
    ]
