# Generated by Django 3.2.9 on 2021-12-08 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20211208_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ExperienceDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
