# Generated by Django 3.2.9 on 2021-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20211211_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='ExperienceDescriptionOne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
